# Instructions to run:
# cd to folder containing this file
# conda env create
# source activate deeplearning 

name: deeplearning 
channels:
- defaults
dependencies:
- python=3.6
- pip==9.0.1
- numpy==1.14.1
- jupyter==1.0
- matplotlib==2.1.2
- scikit-learn==0.19.1
- scipy==1.0
- pandas==0.22
- pillow==5.0.0
- seaborn==0.8.1
- h5py==2.7.1
- pytest==3.4
- flask==0.12
- virtualenv==15.1
- pip:
  - tensorflow==1.5
  - keras==2.1.4
